### ISSUE TITLE
プログラム設計 Sceneを管理するクラス

### ISSUE THREAD

**Issue by Sharoku-haga** [TeamT-SEN/T-SEN#15]
とりあえずSceneを管理するクラスであるSceneManagerを大まかに設計したので、一旦あげてみました。
メンバ変数、GamaDataManagerとFileSaveLoadの中はまだ考え中です。
変数名が変だから変更したらいいなどといったどんなこと小さなことでもいいので意見をお願いします。
![twar scenemanager class](https://cloud.githubusercontent.com/assets/20719722/19466781/67ad1b64-9548-11e6-810e-07b55cc12ff3.png)
![twar scenemanager sequence](https://cloud.githubusercontent.com/assets/20719722/19466786/6ee7affc-9548-11e6-8a0d-55eb258163e6.png)

**Comment by kakeru4** [comment]
特に問題ないと思います。

**Comment by kawaguchi0115** [comment]
大丈夫だと思います。

**Comment by taishi-matsumura** [comment]
@Sharoku-haga 
西井ライブラリを基に色んな人が手を加えてきた旧ドラキンと同様ですね(笑)  

以下、指摘事項。
- クラス図
  - [x] SceneFactory  
    SceneManagerが持ってるわけじゃないので、そこの黒菱はちょっと違うと思います。 
    Factoryは要はシングルトンなので、それがわかるように(Constructorがprivateであることを明記する等)して下さい。
  - [x] FileSaveLoad  
    クラス名がイヤ。何のファイルかわからんし。セーブデータのファイルだけを扱うのなら、SaveDataManagerとかでどうでしょう？
- シーケンス図
  - [x] Sceneのライフラインが変。Activeになっている範囲をメッセージ(関数)の処理中だとするのなら、インスタンスが生存している期間を縦の点線で明記して下さい。  
    この場合だと、SceneはFactoryからnewされるはずなのでそこで初めて図に登場して、SceneManagerからdeleteされるタイミングで図からいなくなるはず。  
    ついでに言うと、FactoryからSceneに出てる線がおかしい。破線はreturnの線です。
  - [x] GraphicDeviceを登場させてSceneManagerから線引いたのなら、Draw()の中からもGraphicDeviceに線引いて下さい。
  - [x] Renderの中のaltはopt。altは二択以上のときに使います。
  - [x] 描画処理のalt(正しくはoptですが)がDrawだけにかかっている理由(Start/EndRenderを現在のStep関係無しに実行する理由)を教えて下さい。

**Comment by Sharoku-haga** [comment]
@taishi-matsumura 
内容確認致しました。
ご指摘ありがとうございます。
・SceneFactoryは修正しておきます。
・名前はSaveDataManagerに変更します
・optの存在を忘れてました。書き直します
・Start/EndRenderは完全に書き間違いです
修正に入ります。
後 1つ質問があるのですが、GraphicsDeviceといったライブラリ関連もクラス図に書いた方がよいのでしょうか？
今回はクラス図にライブラリを書くとごちゃごちゃして見にくくなると思い、書きませんでした。

**Comment by taishi-matsumura** [comment]
> 今回はクラス図にライブラリを書くとごちゃごちゃして見にくくなると思い、書きませんでした。

確かに。
もし書くなら「描画ライブラリ」とかで纏めてしまっていいと思います。その場合は矢印には関数名では無く要求の内容が日本語で書かれることになるかな。
或いはそもそも登場人物として出さずにコメントで「ライブラリに描画処理要求を出す」とか書いても良いかと。

シーケンス図は「いつ」「誰と誰が」「どんな」やりとりをするのかを表現する図なので、それがわかればOKですし、逆にどんなに詳しく書いていても却ってわかりにくくなるようならNGです。
「これでわかるやろ！っていうか、わかってくれ！！」というゴリ押しが必要なシーンもありますが、まぁ最初なのできっちりやりましょか～

**Comment by Sharoku-haga** [comment]
了解しました。
ライブラリは、Libraryと表記して コメントで処理の要求の簡単な説明をつける形でまとめてみます
質問に答えていただきありがとうございました。

**Comment by taishi-matsumura** [comment]
> ・Start/EndRenderは完全に書き間違いです

シーン切り替え時は一旦黒画面にしたいからなのかな？とか思いましたが、いかがでしょう？
旧ドラキンも同じ作りになっていますね。

**Comment by Sharoku-haga** [comment]
大変恥ずかしい話ですが、そんな意図は特になく普通にPlantUMLで書き間違えただけです。
今回はお分かりの通りドラキンのソースをベースに作成しております。
それを踏まえて自分なりに自分ならこうするという感じでいくつか変更しながら作成してみました。
指摘の部分もこれでよくないかと思い変更した部分になります。
ソースにそういう意味があるとは思いませんでした。
話を聞いてソースの意図を読み切れていないと痛感しています。

**Comment by Sharoku-haga** [comment]
夜分遅くすみません。
下記の図が修正したものになります。意見をお願いします。
SceneFactoryのConstructorですが、privateである印をクラス図につけましたが、わかりにくいと思ったのでコメントに明記しました。
ライフラインですが途中で消す方法が調べてもわからなかったので、とりあえずなくなる時点（delete）を×で示す形になっております。もし、良いサイトがあれば教えていただければ幸いです。
ライブラリはLibraryとしてクラス図とシーケンス図に表記しました。
Start/EndRenderはoptの中に入れてます。黒画面仕様をドラキンのソースで確認してみたら、かなりの違いを感じました。なので、明日にでもチームのメンバーにみてもらいどちらにするか検討します。
![twar scenemanager class](https://cloud.githubusercontent.com/assets/20719722/19478575/0db528aa-957e-11e6-97cb-141bafd32997.png)
![twar scenemanager sequence](https://cloud.githubusercontent.com/assets/20719722/19478582/169d1dc4-957e-11e6-8827-3a9d8c55811a.png)

**Comment by taishi-matsumura** [comment]
> SceneFactoryのConstructorですが、privateである印をクラス図につけましたが、わかりにくいと思ったのでコメントに明記しました。

PlantUMLでクラス図を書くとこんな風になるんですね。確かにわかりにくい。
コメントで対応、良いと思います。

> ライフラインですが途中で消す方法が調べてもわからなかったので、とりあえずなくなる時点（delete）を×で示す形になっております。もし、良いサイトがあれば教えていただければ幸いです。

これもPlantUMLのシーケンス図の仕様ですかね。deleteと×でわかるので良いと思います。

あとは指摘というほどでは無いのですが、クラス図の方、SceneManagerとLibrary/SceneFactoryの関連は単方向だと思うので誘導可能性の矢印を付けてやると良いかも知れません。
[この辺](https://www.ogis-ri.co.jp/otc/hiroba/UMLTutorial/design/do_work/do_work4_1.html)が参考になるかと。
あと、SceneはFactoryによって生成されるので、ここにも関連の線があった方が良いかも。

その他、大筋としては問題無さそうな気がします。
この調子でどんどんクラス設計を進めて下さい！！

**Comment by Sharoku-haga** [comment]
アドバイスありがとうございます。
アドバイスをもとに修正し、今日には修正版をあげておきます。
これからも設計のアドバイスよろしくおねがいします。

**Comment by Sharoku-haga** [comment]
夜分遅くにすみません。
下記の図が修正版となります。
確認お願いします。
クラス図に誘導可能性の矢印を追加しております。
描画開始処理と描画終了処理の位置ですがチームで話し合った結果、旧ドラキン方式でいくことで決まりました。なので前の設計から変更しております。
![twar scenemanager class](https://cloud.githubusercontent.com/assets/20719722/19520423/3743dd7e-964b-11e6-8a79-21408eb28a04.png)
![twar scenemanager sequence](https://cloud.githubusercontent.com/assets/20719722/19520447/474e3304-964b-11e6-8594-de68e6b7df84.png)

**Comment by taishi-matsumura** [comment]
問題無いと思います。

P.S.
小谷たち二年生と喋ってて思い付いたんですが、レビュー依頼出すときに
- [x] 松田
- [x] 川口
- [x] 松村
- [ ] 中地

みたいな感じでタスクリスト使うとわかりやすいかな、と。
今度やってみて下さい。

**Comment by Sharoku-haga** [comment]
了解しました。
タスクリストは今度レビュー依頼を出すときに使ってみます。
では設計のisuuesはcloseします
