### ISSUE TITLE
BattlSceneの設計

### ISSUE THREAD

**Issue by kakeru4** [TeamT-SEN/T-SEN#21]

**Comment by kakeru4** [comment]
BattleSceneの設計に着手します。

**Comment by kakeru4** [comment]
![battlescene](https://cloud.githubusercontent.com/assets/20787881/19674940/6826a2b2-9ac6-11e6-8e80-48ef8e6d241c.png)
今日まで作業してたクラス図です。
何か足りないものがあれば言ってほしいです。
明日バトルシーンの仕様書がもらえると思うので訂正してあげなおしします。

**Comment by Sharoku-haga** [comment]
他国IDと書いてるけど、自国はどうするの？

**Comment by Sharoku-haga** [comment]
EffectクラスをObjectManagerに持たせるのはどうなんだろうか？
個人的にはEffectクラスはそれぞれのオブジェクトに持たしてもいいと思う。
もしくはObjectManagerに持たせるのはEffectクラスを管理するEffectManagerクラスで、そのクラスをそれぞれのオブジェクトにわたすのもいいかなと思う

**Comment by Sharoku-haga** [comment]
UIやけどBattleSceneがもつべきやと思う。ObjectManagerはゲーム内のオブジェクト管理が仕事だと思うから、UIをもつのは変かなと思う。

**Comment by taishi-matsumura** [comment]
以下、通りすがりの人からのコメントです。
「エネミーがいるのにプレイヤーがいないとか、shipなのにememy(海洋生物じゃない)とか、きになるなぁ🤔」

言ってしまえば名前の付け方の話だと思うのですが、
「『エネミー』と対になるのは『船』じゃなくて『プレイヤー』よね？」とか
「『船』と対になるのは『敵』じゃなくて『海洋生物』よね？」とか
そういう話。

**Comment by kakeru4** [comment]
自国についてはまだ考え中です。
ObjectManagerが色々持ちすぎかなと思うので一回消そうかなと思います。
enemyについてなんですけどいい名前が思いつかなかったのでとりあえずenemyにしていました、ややこしくてすみません。

**Comment by kakeru4** [comment]
![battlescene](https://cloud.githubusercontent.com/assets/20787881/19716617/c174e140-9b97-11e6-9f91-61fa23e6ec41.png)
昨日の修正版です。
何かあれば意見ほしいです。

**Comment by taishi-matsumura** [comment]
海洋生物、いいと思います。
個人的にはMarineCreatureとかSeaCreatureとかの方が所謂『クリーチャー』『モンスター』みたいなイメージが湧きますが、その辺はお好みで！

**Comment by kakeru4** [comment]
![battlescene](https://cloud.githubusercontent.com/assets/20787881/19754485/f6068e48-9c48-11e6-8b84-dd2cefc0fb3b.png)
海洋生物の仕様が変更になり海洋生物ではなくゴーレムになったので変更しました

**Comment by Sharoku-haga** [comment]
コーディング作業に入っているのでクローズします。
