### ISSUE TITLE
Sceneを管理するクラスの作成

### ISSUE THREAD

**Issue by Sharoku-haga** [TeamT-SEN/T-SEN#22]
Sceneを管理するクラス、つまりSceneManagerクラスを作成する。
すでにプログラム設計は #15 にて行っております。

**Comment by Sharoku-haga** [comment]
Sceneクラスですが、現在の仕様書をもとに下記の図のSceneに分けようと思っています。
特に問題なければこれでSceneIDを作成します。抜けているScene、あるいはいらないSceneなどの意見があれば連絡お願いします。
![twar scene](https://cloud.githubusercontent.com/assets/20719722/19653718/87c680ea-9a50-11e6-938e-94eaf92da4dc.png)

**Comment by kakeru4** [comment]
特に問題ないと思います。

**Comment by Sharoku-haga** [comment]
Sceneクラスですが、先輩からアドバイスをいただきそれをもとにSceneを下記のように分け直しました。
大きな変更点としてはGameSceneになります。前の設計図にあったゲームに関連あるシーン群は GameSceneの下で管理する形にしました。
後EndRollですが、いいクラス名が思いつかなくこの形にしました。いいクラス名があればお願いします。

![twar scene](https://cloud.githubusercontent.com/assets/20719722/19737631/205f15c0-9bef-11e6-9bcb-9f372fa056dd.png)

**Comment by Sharoku-haga** [comment]
Sceneクラス再編に伴い、SceneManager関連のクラス図とシーケンス図を変更しました。
大きな変更点は、GameDataManagerをなくしたところです。GameDataManagerはGameSceneにもたせる形で考えています。
![twar scenemanager class](https://cloud.githubusercontent.com/assets/20719722/19797334/734d3eb0-9d25-11e6-948d-4c96847342f5.png)
![twar scenemanager sequence](https://cloud.githubusercontent.com/assets/20719722/19797347/8656ef60-9d25-11e6-85df-4eea24efbc63.png)

**Comment by Sharoku-haga** [comment]
SceneManagerはマージしてもらいましたので
クローズします。
