### ISSUE TITLE
Githubの細々した設定

### ISSUE THREAD

**Issue by taishi-matsumura** [TeamT-SEN/T-SEN#3]
どーでもいいことですが、、、
- チームのアイコンを設定して下さい  
  →他のチームと並んだときにわかりにくいので
- リポジトリのDescriptionを設定して下さい  
  →SourceTreeとかでcloneするときに空白だとわかりにくいので

後回しで良いので、上記2点、対応お願いします～

**Comment by kakeru4** [comment]
了解です。
少し後回しになると思いますがやります！

**Comment by kakeru4** [comment]
リポジトリのDescriptionの設定は終わりました！
チームのアイコンはチームロゴが届き次第やりたいと思います！

**Comment by taishi-matsumura** [comment]
GithubのMarkdownを使えばこんなこともできます。
- [x] リポジトリのDescriptionを設定する
- [x] チームのアイコンを設定

参考：
[[新機能] GitHub Flavored Markdown でタスクリストを作れるようになりました](http://github.kyanny.me/1375-task-lists-in-gfm-issues-pulls-comments)

**Comment by kakeru4** [comment]
そんな機能あるんですね。
教えていただきありがとうございます！！

**Comment by kakeru4** [comment]
タスクリストを二つとも満たしましたのでcloseします。

**Comment by taishi-matsumura** [comment]
カッコイイ！！
