### ISSUE TITLE
コーディング規約素案

### ISSUE THREAD

**Issue by Sharoku-haga** [TeamT-SEN/T-SEN#4]
コーディング規約の素案を作りました。
確認と意見があればお願いします。
ソースコーディング規約

・ヘッダーはDoxygenでかく

・Doxyjenで書く際はauthorを書く

・ヘッダーのインクルードガードの#defineはファイル名をすべて大文字、
単語の間は＿で区切る
例
# ifndef CLASS_H
# define CLASS_H

~実装部分~
# endif // CLASS_H   ←コメントで#defineで定義したものをかく

・ローカル変数名は小文字からはじめ、そのあとは単語のはじまりは大文字でかく
例：animalName,humanNum

・ポインタ変数の前にはｐをつける
例：int\* pnum

・関数名は動詞から名づける。そして大文字ではじめる
例：DrawPlayer()

・コメント書く際は //の後は半角スペースをあける
例：// コメント

・ネストの書き方は
｛
   ～実装部分～
｝
と形で書く

・マジックナンバーは極力つかわない。
もしつかうならその数値の意味をかくこと

・ライブラリーのヘッダーは必要な分だけ読み込む

クラスの関連
・クラスのファイル名はクラスの名前をつける

・クラスはフィルターごとにまとめる

・クラスの名の始まりは大文字
例：class Scene

・メンバ変数の頭にはm_をつける
例：m_num

・Getter関数は頭にGetをつけ、そのあとに変数をつける
例：int m_numを取得する場合の関数→int GetNum（）

・Setter関数は頭にSetをつけ、そのあとに変数をつける
例：int m_numを取得する場合の関数→int SetNum（）

・コンストラクタで引数が1つの場合はexplicitをつける

**Comment by kakeru4** [comment]
ありがとうございます。

**Comment by taishi-matsumura** [comment]
ポインタ変数はpNum/m_pNumの方が良くないですか？

**Comment by Sharoku-haga** [comment]
確かにpNum/m_pNumの方がとわかりやすいと思いましたので、wikiの方を修正しました。
ご指摘ありがとうございます。
他にも何かありましたらまたお願いします。
