### ISSUE TITLE
βプレゼン後のリファクタリング

### ISSUE THREAD

**Issue by Sharoku-haga** [TeamT-SEN/T-SEN#41]
#31 のアドバイスなど結構リファクタリングすべき部分があるので、βプレゼン後に一度リファクタリングを行います。

作業内容
・ファイルのコメントを修正
・関数GetInstanceをInstanceへ名前変更
・SceneManagerクラスのソース修正（SCENE_DELETEの処理にnullptr処理をつける）
・無駄なnullptrチェックをなくす
・コーディング規約通りにソースを修正
・GameLibをメンバ変数で持つ→よく使う変数の為

**Comment by taishi-matsumura** [comment]
> ・コーディング規約通りにソースを修正

ずっと言い忘れていたのですが、規約内の

```
・ネストの書き方は

｛

～実装部分～

｝
```

が意味不明です。
「ネスト」という単語を間違って覚えているのだと思います。

「開き中括弧の前には改行を入れる」ということが言いたいのだと推測していますが、、、

**Comment by Sharoku-haga** [comment]
ネストですが改めて自分で調べてみましたが、｛｝のこと勘違いしていたみたいです。
wiki修正しておきました。

**Comment by Sharoku-haga** [comment]
マージしたのでクローズしてます。
