### ISSUE TITLE
弾クラスの設計

### ISSUE THREAD

**Issue by kakeru4** [TeamT-SEN/T-SEN#47]
弾クラスの設計に着手します。
期限11/12まで

**Comment by kakeru4** [comment]
PLに聞きたいことがあるので期限を少し伸ばします。
期限11/16まで

**Comment by kakeru4** [comment]
![bullet](https://cloud.githubusercontent.com/assets/20787881/20294640/f6cc4a26-ab42-11e6-8945-011ffc2da56b.png)
![bullet](https://cloud.githubusercontent.com/assets/20787881/20294639/f6cb50e4-ab42-11e6-925b-9000dbeba932.png)
現状のBulletのクラス図とシーケンス図を作ったのであげます。
DamageCheckの引数は明日決めます。
シーケンス図についてなんですけど自分の中であんまりしっくり来てないんでなんでもいいんで意見ください！！

**Comment by Sharoku-haga** [comment]
弾のControl関数とDraw関数って、どこでよぶの？

**Comment by Sharoku-haga** [comment]
DamageCheck関数ってどういう関数なの？
後、関数は動詞はじまりでお願いします

**Comment by Sharoku-haga** [comment]
deleteも少しおかしい気がする。deleteするタイミングはどうするのかという疑問があります。
このシーケンス図やとnewした後にすぐdeleteする流れになっていると思う。

**Comment by kakeru4** [comment]
Sharoku-hagaさんの意見を参考に作り直します。

**Comment by taishi-matsumura** [comment]
提案なのですが、
設計フェーズでも成果物としてastahのプロジェクトファイルなりPlantUMLのソースコードなりpng画像なりをgitにコミットするはず。
であれば、それ用にbranch切ってプルリク出して作業した方が、レビュー履歴なんかも見やすくないですか？

**Comment by kakeru4** [comment]
確かにプルリクでやったほうが見やすいと思うのでbranch切ってプルリクあげます。

**Comment by kakeru4** [comment]
実装に入ってるのでcloseします。
