### ISSUE TITLE
β版のリリースお願いします

### ISSUE THREAD

**Issue by taishi-matsumura** [TeamT-SEN/T-SEN#49]
[キンクラのissue](https://github.com/KingdomCraft-1/KingdomCraft/issues/108)を参考に、β版のリリースをお願いします。
Releaseビルドした実行ファイル(DLL埋め込んだもの)も添付しておいて下さい。

**Comment by kakeru4** [comment]
Releaseを貼りましたがこれでいいのかわからないので確認お願いします。

**Comment by taishi-matsumura** [comment]
最新ソースコードと実行ファイルが貼られているので問題無いと思います！

**Comment by taishi-matsumura** [comment]
現状、実行ファイルが動かないので再オープンします。

以下、状況。
1. exeがDLできない  
   →tag名から日本語を抜くとDLできるようになった
2. DLしたexeが実行できない  
   →よくよく考えたら当然ですが、exeファイルだけでは動きませんね。  
   　画像やらモデルデータやらが必要なので、exe単体ではなくそいつらも纏めてzipにしてUPするしか無いかな。

で、纏めるにあたって、フォルダ階層を考え直した方が良いような気がします。
ソースコード的にはプロジェクトファイルを起点にしたpathで書きますが、
デバッガ使用時以外はexeファイル起点で見たpathになるのでその辺りも考慮して階層決めて下さい。

**Comment by kakeru4** [comment]
zipであげましたが僕のパソコンではダウンロードできませんでした・・・

**Comment by kakeru4** [comment]
Sourse codeのzipの方にexeがありますのでそれでいいですかね？
自分であげた方はなぜかダウンロードできないんで・・・

**Comment by taishi-matsumura** [comment]
うわ、ほんまや、SourceCodeのzipの中にexe入ってる…
いかがなものかと思うけど、今回は急なリリース依頼だったしpre-releaseだし、まぁいいか…

γのリリースまでに手法確立しておいて下さいね～

**Comment by taishi-matsumura** [comment]
zipに固めてアップロードしただけですが、いけたっぽいです。
ついでに、不要なタグ消しときました。
