### ISSUE TITLE
FBXのライブラリ作成

### ISSUE THREAD

**Issue by kakeru4** [TeamT-SEN/T-SEN#5]
FBXのライブラリ作成をお願いします！

**Comment by taishi-matsumura** [comment]
DXライブラリの中にFBXのparserが入っているので参考になるかも知れません。
[ここ](http://dxlib.o.oo7.jp/dxdload.html)の一番下からDLできます。
解凍した中にあるDxModelLoader1.cppがFBXファイルの読み込みプログラムだそうです。

**Comment by Sharoku-haga** [comment]
DLしてソース確認致しました。
解析してライブラリの参考にしたいと思います。
情報ありがとうございます。

**Comment by kakeru4** [comment]
マージしましたのでcloseします。
