### ISSUE TITLE
ＵＭＬの学習

### ISSUE THREAD

**Issue by ichikawaryouya0719** [TeamT-SEN/T-SEN#58]
松村先生の課題「理論2回目」を使用してＵＭＬの学習をします。
使用するツールはastahを使用します。

期限は11/22(火曜日)までとします。
完了条件は芳我さん、に合格を頂くことで完了とします。

**Comment by ichikawaryouya0719** [comment]
![001](https://cloud.githubusercontent.com/assets/22762498/20416693/d994bd74-ad83-11e6-81f2-03df93a023ca.png)

クラス図の制作途中です。
一日の作業終わりにUPするようにします。（課題終了まで）
ご指摘、アドバイス頂ければ有難いです。

**Comment by Sharoku-haga** [comment]
TitleSceneManagerクラスのTitleSceneManager関数？やけど、型booleanであってる？
これってコンストラクタじゃないのかな？

**Comment by ichikawaryouya0719** [comment]
ご指摘ありがとうございます。
関数です。
修正しました。
一日の作業終わりにＵＰします⇒確認してからＵＰします。
に訂正します。

**Comment by Sharoku-haga** [comment]
TitleTimeManagerのメンバ関数やけど、TitleTimeManagerってコンストラクタやと思うから、void型ではないと思う。
後、TitleTimeManagerのクラス名間違っている。

**Comment by ichikawaryouya0719** [comment]
ご指摘ありがとうございます。
修正しました。

**Comment by Sharoku-haga** [comment]
ごめんなさい。上記でTitleSceneManagerとか書いたけど、TitleSelectManagerの間違いでした。
後、TitleSelectManagerのコンストラクタがprivateになっているけどそれで大丈夫かな？

**Comment by ichikawaryouya0719** [comment]
ご指摘ありがとうございます。
修正しました。

**Comment by ichikawaryouya0719** [comment]
![002](https://cloud.githubusercontent.com/assets/22762498/20424851/3e48bd92-adbb-11e6-9d17-fa9ff717e9a9.png)

理論２回目のクラス図です。
ご指摘等頂けれたら幸いです。

**Comment by taishi-matsumura** [comment]
@ichikawaryouya0719 「芳我とかに揉んでもらってから出直して来い」と言いたいところですが、それそろ芳我が可哀想なので @masami-sugao 女史にお願いすることにしました。
いま隣でゴリゴリ指摘書いてくれてるのでしばしお待ち下さいませ。

**Comment by masami-sugao** [comment]
@taishi-matsumura 先生の依頼でやってきました。
答えは書かないようにしてるのでもう少し考えてみて下さいな。
- 全体
  - Privateメンバ変数が記載されているものと記載されていないものがありますが、どういう書き分けですか？
  - 関数の順序ですが、個人的にはコンストラクタは1番上に書いてあると見やすいです。
  - デストラクタの記載がないのはなぜですか？
  - boolとbooleanが混在しているのはなぜですか？
  - 関連の矢印が全体的におかしいです。
- TitleTimeManager
  - `Control()`の返却値がおかしいです。
- Scene
  - `Control()`の書き方おかしいです。  
    astah暫く触ってないですが、astahの機能使って書いたらこんなことにはならない気がしますが…。
  - 変数の記載がないです。  
- SceneManager
  - コンストラクタの引数おかしいです。  
- TitleSelectManager
  - コンストラクタの引数おかしいです。  
  - `Control()`の書き方おかしいです。  
- TitleName
  - コンストラクタの引数おかしいです。  
  - コンストラクタしか書いてないのはなぜ…??
- TitleScene
  - コンストラクタの引数おかしいです。  
  - `Control()`の書き方おかしいです。

**Comment by ichikawaryouya0719** [comment]
![005](https://cloud.githubusercontent.com/assets/22762498/20492469/3a83b0d2-b058-11e6-96d9-f9e4458653e7.png)


ご指摘ありがとうございます。
週末忙しくて修正が遅れましたができる限り修正しました。

boolとbooleanはイコールで考えていました。どちらでも良いと自分で解釈していましたがわかりにくいので今後はboolで統一します。

privateの変数の書き分けですがＬｉｂｒａｒｙ*等は書かなくても良いと思っていました。
今後は全て書くようにします。

関数の順修正しました。
コンストラクタからだととても見やすくなりました。
アドバイスありがとうございます。

デストラクタの不記載ですがこれも書かなくて良いと思っていました。
今後書くようにします。

今回は多くのご指摘を頂きありがとうございました。
とても勉強になりました。
今後も先生方やクラスメイト、自分で調べて理解度を高めたいと思います。

**Comment by ichikawaryouya0719** [comment]
![006](https://cloud.githubusercontent.com/assets/22762498/20509283/ea289d48-b0aa-11e6-822b-936cce461f5d.png)

修正しました。

**Comment by Sharoku-haga** [comment]
TitleSceneのコンストラクタの引数名が違うと思う。

**Comment by Sharoku-haga** [comment]
なんか前にあげたクラス図の方が修正されているような気がする。
今あげたクラス図だとbooleanも表記されてるよ。

**Comment by Sharoku-haga** [comment]
後、SceneとSceneManagerの間の関係も書いた方がいいと思う

**Comment by ichikawaryouya0719** [comment]
![008](https://cloud.githubusercontent.com/assets/22762498/20509742/2c745f72-b0ae-11e6-9de3-d92bd16d9651.png)
ご指摘ありがとうございます。

前回データがロストした時の名残です。
私の確認不足が原因です。

修正版を上げます。

**Comment by ichikawaryouya0719** [comment]
![009](https://cloud.githubusercontent.com/assets/22762498/20510312/a61fbbb0-b0b2-11e6-959b-01ce5599a075.png)

SceneとSceneManagerの関係がおかしかったので修正しました。

**Comment by ichikawaryouya0719** [comment]
![009](https://cloud.githubusercontent.com/assets/22762498/20590813/b3d4656e-b268-11e6-8515-ea74f40bf8cc.png)

修正しました。

**Comment by Sharoku-haga** [comment]
大丈夫だと思いますので、クローズしておきます。
