### ISSUE TITLE
チームロゴの設計

### ISSUE THREAD

**Issue by ichikawaryouya0719** [TeamT-SEN/T-SEN#75]
チームロゴのクラス図とシーケンス図、を制作します。

期限は11/28です。

**Comment by ichikawaryouya0719** [comment]
![logoscene01](https://cloud.githubusercontent.com/assets/22762498/20675853/1a085a82-b5d1-11e6-8417-6c385917c293.png)

チームロゴのクラス図です。
ご確認お願いします。

**Comment by ichikawaryouya0719** [comment]
![0](https://cloud.githubusercontent.com/assets/22762498/20695330/6d540e68-b62e-11e6-9547-48360402fa19.png)
クラス図修正しました。

**Comment by kakeru4** [comment]
TeamLogoクラスのLogoInit関数とメンバ変数ってなんですか？
あとLogoSceneクラスとSceneクラスのControl関数の型が前についているのはなぜですか？

**Comment by ichikawaryouya0719** [comment]
![010](https://cloud.githubusercontent.com/assets/22762498/20770940/cedb96a8-b78a-11e6-9bb1-51546a4617dc.png)

ご指摘ありがとうございます。
修正しました。

**Comment by ichikawaryouya0719** [comment]
![002](https://cloud.githubusercontent.com/assets/22762498/20770960/e361d0f6-b78a-11e6-8f65-898417e47c94.png)

シーケンス図です。
ご確認お願いします。

**Comment by Sharoku-haga** [comment]
とりあえずGameLibのSetVtxColorの関数メッセージの方向がおかしいと思う。
この図で見る限りGameLibがLogoSceneにあるSetVtxColor関数をよんでいるというふうに見えるのだけど、SetVtxColorはGameLibの関数なはずなので方向は違うと思う。
後個人的な考えかもしれないが、GameLibが左端にくるのはいやな感じがする。
このシーケンス図はLogoSceneがメインかと思いますが、GmaeLibが左にあるとGameLibがメインかなと思ってしまいます。
シーケンス図は呼び出しメッセージが左から右の方向にいくので、自分としてはメインとなるクラスは左端に書いてほしいと思います。
他にも結構指摘する点はありますが、 #15 のやり取りやネットを参考に自分でもう一度考えてみてください。
自分もシーケンス図は苦手なのでつらい気持ちはわかりますが、頑張ってください。

**Comment by ichikawaryouya0719** [comment]
![004](https://cloud.githubusercontent.com/assets/22762498/20785154/06eb6a4e-b7e2-11e6-8098-a59c8096fc49.png)

芳我さんにご指摘頂いた箇所修正しました。
ご確認お願いします。

**Comment by taishi-matsumura** [comment]
リターンメッセージの分岐について。
ご参考に→https://astah-users.change-vision.com/ja/modules/xhnewbb/viewtopic.php?topic_id=1334

**Comment by ichikawaryouya0719** [comment]
![011](https://cloud.githubusercontent.com/assets/22762498/20821063/fcd32a46-b882-11e6-98b0-a7c87a34455b.png)
@taishi-matsumura 先生からご指摘頂いた箇所修正しました。

**Comment by ichikawaryouya0719** [comment]
![default](https://cloud.githubusercontent.com/assets/22762498/20822894/11333f1c-b892-11e6-9d9a-4a93f51d0c35.png)
![default](https://cloud.githubusercontent.com/assets/22762498/20822895/12d73abc-b892-11e6-8788-ac08deeb8f17.png)

@taishi-matsumura 先生かご指摘頂いた箇所修正しました。
二枚目は終了条件時です。

**Comment by Sharoku-haga** [comment]
シーケンス図確認致しました。
これで図が完成ならば、コーディング作業にはいってください。
作業の手順ですが、
このisuuesをクローズする
                ↓
#23 もクローズする。
                ↓
コーディングする旨を書いたisuuesを作成する
                ↓
リモートブランチもpremasterをチェックアウト(masterブランチじゃないので注意)
                ↓
premasterブランチから新たにブランチをきる
                ↓
そのブランチで少し作業（コメント追加など)してコミットする。
                ↓
プルリクエストを作成する（題名の頭には[WIP]をつけること）
                ↓
作業を続けていき、完了したら[WIP]をはずし、レビューしてもらう
   
でお願いします。
ちなみになぜpremasterからブランチをきるのかというと
 kakeru4がそのブランチでTeamLogoクラスのファイルを作成してくれているためです。

わからないことがあれば、isuuesもしくはラインで連絡ください。

**Comment by ichikawaryouya0719** [comment]
コーディングにはいるのでクローズします。
