### ISSUE TITLE
READMEにバッジ貼ってみてはいかが？

### ISSUE THREAD

**Issue by taishi-matsumura** [TeamT-SEN/T-SEN#90]
READMEに下記のようなバッジ貼るのが流行りみたいです。
![](https://img.shields.io/badge/DirectX%20SDK-9.0c(June2010)-brightgreen.svg)
![](https://img.shields.io/badge/FBX%20SDK-2016.1-orange.svg)

仕事で使っているiPhoneアプリ用のライブラリのリポジトリなんかはこんな感じ
Alamofire：https://github.com/Alamofire/Alamofire
RxSwift：https://github.com/ReactiveX/RxSwift

本来、バッジはリポジトリのステータスを表すためのもののようですが、[Sheilds IO](http://shields.io/)で自由に作れます。
僕が愛用しているSpacemacsのREADMEなんかはグッズの通販ページへのリンクとかもあるので、自由ですね。
Spacemacs：https://github.com/syl20bnr/spacemacs

γのリリースのタイミングで検討してみて下さい～

参考：[Githubリポジトリにいっぱいバッジをつける方法](http://blog.muuny-blue.info/1ae5168b14a6091d623291902ac36e7c.html)

**Comment by kakeru4** [comment]
教えていただきありがとうございます。
チームで検討してみます。

**Comment by kakeru4** [comment]
バッジ貼ってみたので確認お願いします。

**Comment by taishi-matsumura** [comment]
いいと思います。

VSのとこは書くとしたら「2013 Community」かな。
「2013」だけでもいいです。
