### ISSUE TITLE
GameDataManagerとGameStateManagerのクラスの作成

### ISSUE THREAD

**Issue by kakeru4** [TeamT-SEN/T-SEN#99]
BattleDataManagerとBattleStateManagerのクラスの作成をお願いします。

**Comment by Sharoku-haga** [comment]
GameStateManagerとGameDataManagerですが、これはBattleで使用できるような段階(実装)までもっていくということでいいですか？
それともとりあえずファイルだけ作成しておいておくだけでいいですか？

**Comment by kakeru4** [comment]
申し訳ないです。
BattleStateManagerとBattleDataManagerでお願いします。
Monsterができ次第で大丈夫なので実装でお願いします。

**Comment by Sharoku-haga** [comment]
了解しました。
ではファイルだけ作成しておきます。
#100 でissueきりました。

**Comment by kakeru4** [comment]
了解です。
マージしましたのでcloseします。
